### PR TITLE
Update got dependency to ^11.8.5

### PR DESCRIPTION
**Pull request by pavleprica**
Hey there @VictorTaelin :)

Basically just went with updating got to latest, npm i, npm audit fix. We have overridden the got dependency in our project and it works fine, but do you perhaps have a suggestion what's the best way to test it? :)

Other than that, if you deem it ok, maybe we can merge in and publish a new release? :)

I have also taken the liberty to add a small github actions file, just so it runs the most basic check while building it.

### CODE REVIEW

**Comment by Jonahss** [comment]
@VictorTaelin hasn't been responding. There are [others who would like to update this dependency](https://github.com/VictorTaelin/swarm-js/pull/42#issuecomment-1222453095) (plus the code itself is pretty stale). Perhaps you should consider working with @israelboudoux to fork this repo and establish it as the updated one?

**Comment by pavleprica** [comment]
@Jonahss thanks for reaching out!

I communicated briefly with @VictorTaelin months ago. He pointed out that this could be a very temporary solution and that we should start migrating to its [successor](https://erebos.js.org/). Even though a chance to work with @israelboudoux sounds tempting, if we were to create the fork we might switch to the successor either way. :) :D

**Comment by israelboudoux** [comment]
Haha, thank you @pavleprica, I imagine that working with you would be great, but I'm rushing with tons of things at the moment. I don't know if I could be helpful.

**Comment by VictorTaelin** [comment]
Sorry guys, I don't work at Ethereum anymore. I've been very busy these days, and I'm also facing some health issues. This lib should *not* be used anymore (see the README). The problem with accepting PRs to fix these issues is that I need to review in order to make sure there isn't some malicious code sneaking in. I'll accept this PR since it seems safe to just update `got`, but I still advise against using this lib, since I can not guarantee I'll be able to maintain it.

**Comment by pavleprica** [comment]
Hey Victor, thanks for reaching out. 

I hope everything will be ok and quite confident you will tackle it!

**Pull request merged**
