### PR TITLE
Replaces deprecated bzzr protocol with bzz-raw

### LINKED ISSUE #17: Implement URI scheme updates
The `bzzr` URI scheme has been [deprecated in favour of `bzz-raw`](https://github.com/ethereum/go-ethereum/pull/15667).

`bzzr` is still supported for now but an upgrade path to implement `bzz-raw` should be considered.

As not all consumers of the `swarm-js` library will use Swarm/Geth ^1.8.0, use of the `bzzr` scheme cannot simply be replaced with `bzz-raw`. Perhaps the scheme update should be made in a major release and documented in the readme.

@MaiaVictor - What are your thoughts?

### PR DESCRIPTION
**Pull request by JirkaChadima**
Closes #17 

In the [latest documentation](http://swarm-guide.readthedocs.io/en/latest/apireference.html#http), `bzzr` is not even mentioned.

edit: I'm not sure if I have to replace the protocol in `lib` dir as well as I'm not familiar with the build process.

### CODE REVIEW

**Comment by evertonfraga** [comment]
Hi @JirkaChadima, thanks for your contribution.

Please run `npm run bundle` in order to update `/lib` directory
https://github.com/MaiaVictor/swarm-js/blob/master/package.json#L8

**Comment by JirkaChadima** [comment]
Ok, so `bundle` itself did not work. I tried run the `build` script. But that does not work either.

Furthermore I had to manually install `browserify` and `closurecompiler` which should be declared in `devDependencies`.

What actually compiles all the stuff into `lib` dir, is the `babel` command. So I ran both `babel` and `build`.

**Comment by agazso** [comment]
Hi, I run into to same issue. The current version of Swarm returns 400 when you try to download something with SwarmJS and it returns 404 when you try to upload. It's because SwarmJS uses the deprecated bzzr:/ schema.

As far as I see this PR fixes the issue, but for some reason it's not merged. Can I help somehow to resolve this situation?

**Comment by JirkaChadima** [comment]
ping @evertonfraga

**Pull request merged**
