### PR TITLE
replace deprecated tar.gz module with tar module

### LINKED ISSUE #10: Remove `tar.gz` dependency
When installing web3.js I'm getting: `npm WARN deprecated tar.gz@1.0.7: ⚠️  WARNING ⚠️ tar.gz module has been deprecated and your application is vulnerable. Please use tar module instead: https://npmjs.com/tar`

According to its [repo](https://github.com/alanhoff/node-tar.gz). Tar.gz it's not maintained anymore.

### PR DESCRIPTION
**Pull request by Jonahss**
fixes #10 

I ran the test for this.

```
> let test = require('./lib/files.js').test
> test().then(console.log)
// true
```

Looks good :)

### CODE REVIEW

**Comment by lukehedger** [comment]
Also noticed that the `tar.gz` package is used for [preparing](https://github.com/MaiaVictor/swarm-js/blob/e53f2d593784fac39a83644c85c4dbcd042d0e5a/scripts/prepareArchives.js#L84) and [fetching](https://github.com/MaiaVictor/swarm-js/blob/43e27cdb3bfd537ab599c188e38afa81e870108a/src/swarm.js#L283) Swarm binaries, so guess these methods will break due to removal of `tar.gz`. Haven't investigated whether a simple swap with `tar` will work.

**Comment by Jonahss** [comment]
the functions on the module should be interchangeable.

**Comment by lodo1995** [comment]
@evertonfraga, @MaiaVictor, is there any problem with this PR? It's been proposed together with #13, which got merged recently. It is a very important PR for the same reason as that one, i.e. that the deprecated and unmaintained package gets fetched a lot, as `swarm-js` is a dependency of `web3`. And of course, the associated deprecation message is shown to basically all Ethereum developers out there...

**Comment by evertonfraga** [comment]
Hi @lodo1995 I took ownership of this repo from @MaiaVictor, as he's super busy at this moment. 

I am reviewing and testing it now.

**Comment by evertonfraga** [comment]
I implemented those changes myself.

**Pull request merged**
